ajout de la partie mobile, script packetage
CQEN-QDCE/exp-dev-distribue pull request #6
Opened 2024-02-05 21:54 UTC by yonepv

2024-02-08 17:04 UTC, gagf01 requested changes

2024-02-08 17:04 UTC, gagf01 commented on app/readme.md
> +Pour produire la version mobile de l'application, l'outil d'exécution **capacitor** (d'[Ionic](https://capacitorjs.com/)) s'avère comme l'outil le plus générique ou neutre à être utilisé.
```suggestion
Pour produire la version mobile de l'application coquille, la couche d’accès multi-plateformes **capacitor** (d'[Ionic](https://capacitorjs.com/)) est utilisé comme outil d'empaquetage.
```

2024-02-08 17:04 UTC, gagf01 commented on app/readme.md
> +Dans le cas de cette application, il faut exécuter le script [pack_app.sh](scripts/mobile/pack_app.sh) pour générer la version packagée de l'application qui pourra être téléchargée par exemple à Goog
```suggestion
Dans le cas présenté, le script [pack_app.sh](scripts/mobile/pack_app.sh) permet de générer la version Android de l'application qui pourra être téléchargée, par exemple, à Google Play.
```

2024-02-08 17:04 UTC, gagf01 commented on app/readme.md
> +- Information additionnelle: C'est recommandé de générer une pair de clès pour encrypter et signer le composant qui sera téléchargé et publié pour installation en version mobile.
```suggestion
- Information additionnelle: Il est recommandé de générer une paire de clés pour encrypter et signer le composant qui sera téléchargé et publié pour installation en version mobile. Les outils utilisés sont disponibles dans le [Java Development Kit](https://fr.wikipedia.org/wiki/Java_Development_Kit). Nous recommandons celle du project [OpenJDK](https://openjdk.org/).
```

2024-02-08 17:04 UTC, gagf01 commented on app/readme.md
> +    * Génération d'une pair de clés avec l'outil keytool:
```suggestion
    * Génération d'une paire de clés avec l'outil `keytool`:
```

2024-02-08 17:04 UTC, gagf01 commented on app/readme.md
> +    * Signature du composant (de l'application packagée) à être téléchargé:
```suggestion
    * Signature de l'application Android à être téléchargée:
```

2024-02-08 17:04 UTC, gagf01 commented on app/scripts/mobile/pack_app.sh
Il faudrait traduire les commentaires en français vu que notre dépôt est plus une démonstration qu'un prototype.

2024-02-09 15:30 UTC, yonepv commented on app/scripts/mobile/pack_app.sh
https://github.com/CQEN-QDCE/exp-dev-distribue/commit/3d7db4d2ad51ce5a0a8e4b28e14c19a7bb1f3728

2024-02-09 15:39 UTC, gagf01 approved these changes

2024-02-09 15:40 UTC, merged